### ISSUE TITLE
Script error discovering CRLs

### ISSUE THREAD

**Issue by ccoleman1200** [rafabu/SCOM-PKICertificateMP#31]
Great MP! I have used an override to enable CRL discovery for specific My certificate stores however the CRLs are not being discovered. The event log is reporting an error when running the CRL discovery script. This is occurring on Windows Server 2016. Do you have any suggestions?

Event id 4509
The constructor for the managed module type "Microsoft.EnterpriseManagement.Modules.PowerShell.PowerShellProbeActionModule" threw an exception. This module was running in rule "SystemCenterCentral.Utilities.Certificates.LocalScriptProbe.CRL.Discovery" running for instance "Personal Computer Certificate Store" with id:"{3A584729-30C6-41D6-16F8-173ECF12AD72}" in management group "XXXXXXX".
 
 The exception text is:
 Microsoft.EnterpriseManagement.HealthService.ModuleException: Failed to parse module configuration, please see inner exception for details. ---> System.Xml.XmlException: 'EndElement' is an invalid XmlNodeType. Line 1124, position 860.
   at System.Xml.XmlReader.ReadElementString(String name)
   at Microsoft.EnterpriseManagement.Modules.PowerShell.PowerShellProbeActionModule.ReadParametersXml(XmlReader reader)
   at Microsoft.EnterpriseManagement.Modules.PowerShell.PowerShellProbeActionModule..ctor(ModuleHost`1 moduleHost, XmlReader configuration, Byte[] previousState)
   --- End of inner exception stack trace ---
   at Microsoft.EnterpriseManagement.Modules.PowerShell.PowerShellProbeActionModule..ctor(ModuleHost`1 moduleHost, XmlReader configuration, Byte[] previousState)

**Comment by quilter-MattCreighton** [comment]
I get the same, I am also trying to enable CRL discovery - anyone got a work around to get this to work please?
